# Search

		wearNames = ""
		for i in xrange(self.WEAR_COUNT):

# Replace flagList for:

		flagList = (item.IsWearableFlag(item.WEARABLE_BODY),
					item.IsWearableFlag(item.WEARABLE_HEAD),
					item.IsWearableFlag(item.WEARABLE_FOOTS),
					item.IsWearableFlag(item.WEARABLE_WRIST),
					item.IsWearableFlag(item.WEARABLE_WEAPON),
					item.IsWearableFlag(item.WEARABLE_NECK),
					item.IsWearableFlag(item.WEARABLE_EAR),
					item.IsWearableFlag(item.WEARABLE_UNIQUE),
					item.IsWearableFlag(item.WEARABLE_SHIELD),
					item.IsWearableFlag(item.WEARABLE_ARROW),
					item.IsWearableFlag(item.WEARABLE_PENDANT))

# Search

})
		
	ATTRIBUTE_NEED_WIDTH = {
		
# Add after
		
	AFFECT_DICT.update({
		item.APPLY_ATTBONUS_ELEC : localeInfo.TOOLTIP_APPLY_ATTBONUS_ELEC,
		item.APPLY_ATTBONUS_FIRE : localeInfo.TOOLTIP_APPLY_ATTBONUS_FIRE,
		item.APPLY_ATTBONUS_ICE : localeInfo.TOOLTIP_APPLY_ATTBONUS_ICE,
		item.APPLY_ATTBONUS_WIND : localeInfo.TOOLTIP_APPLY_ATTBONUS_WIND,
		item.APPLY_ATTBONUS_EARTH : localeInfo.TOOLTIP_APPLY_ATTBONUS_EARTH,
		item.APPLY_ATTBONUS_DARK : localeInfo.TOOLTIP_APPLY_ATTBONUS_DARK,
		
		item.APPLY_RESIST_HUMAN : localeInfo.TOOLTIP_APPLY_RESIST_HUMAN,
		item.APPLY_RESIST_SWORD_REDUCTION : localeInfo.TOOLTIP_APPLY_RESIST_SWORD_REDUCTION,
		item.APPLY_RESIST_TWOHAND_REDUCTION: localeInfo.TOOLTIP_APPLY_RESIST_TWOHAND_REDUCTION,
		item.APPLY_RESIST_DAGGER_REDUCTION : localeInfo.TOOLTIP_APPLY_RESIST_DAGGER_REDUCTION,
		item.APPLY_RESIST_BELL_REDUCTION : localeInfo.TOOLTIP_APPLY_RESIST_BELL_REDUCTION,
		item.APPLY_RESIST_FAN_REDUCTION : localeInfo.TOOLTIP_APPLY_RESIST_FAN_REDUCTION,
		item.APPLY_RESIST_BOW_REDUCTION : localeInfo.TOOLTIP_APPLY_RESIST_BOW_REDUCTION,
		item.APPLY_ATTBONUS_ZODIAC : localeInfo.TOOLTIP_APPLY_ATTBONUS_ZODIAC,
		item.APPLY_ATTBONUS_DESERT : localeInfo.TOOLTIP_APPLY_ATTBONUS_DESERT,
		item.APPLY_ATTBONUS_INSECT : localeInfo.TOOLTIP_APPLY_ATTBONUS_INSECT,
		item.APPLY_RESIST_CLAW_REDUCTION : localeInfo.TOOLTIP_APPLY_RESIST_CLAW_REDUCTION,
	})
