// Search

};

enum EPKModes
{


// Add before

#ifdef ELEMENT_NEW_BONUSES
	POINT_ATTBONUS_ELEC,
	POINT_ATTBONUS_WIND,
	POINT_ATTBONUS_EARTH,
	POINT_ATTBONUS_DARK,
	POINT_RESIST_HUMAN,

	POINT_RESIST_SWORD_REDUCTION,		
	POINT_RESIST_TWOHAND_REDUCTION,	
	POINT_RESIST_DAGGER_REDUCTION,	
	POINT_RESIST_BELL_REDUCTION,		
	POINT_RESIST_FAN_REDUCTION,		
	POINT_RESIST_BOW_REDUCTION,

	POINT_ATTBONUS_ZODIAC,
#ifdef ENABLE_WOLFMAN_CHARACTER
	POINT_RESIST_CLAW_REDUCTION,
#endif
#endif
